### ISSUE TITLE
discussion: the minimal C++ compiler support

### ISSUE THREAD

**Issue by neverchanje** [IppClub/Dora-SSR#25]
As of today, I believe there is no reason to use compiler <= C++17. We can use C++20 features if necessary.

Once we determined the minimum required C++ version, we need to document it in somewhere, e.g, #26.

**Comment by pigpigyyy** [comment]
The updating for minimal C++ compiler standard requires testing on all building platforms and tool-chains. There are GCC on Linux, Clang on macOS and iOS and Android NDK(modified version of GCC and Clang) to be tested for newer C++ standard feature support.
