### ISSUE TITLE
CMake Support

### ISSUE THREAD

**Issue by paulocoutinhox** [IppClub/Dora-SSR#7]
Very nice project.

1 - Can you add support for CMake?
2- There is any real game with it? Do you have more samples?

Thanks.

**Comment by pigpigyyy** [comment]
CMake support is currently only working with Linux build. You can find related files here https://github.com/pigpigyyy/Dorothy-SSR/tree/main/Project/Linux

This project is still under heavy development, may be unstable for the moment. There is a real open source game project with it. You can find the game project descriptions here (sorry for the docs without English translations for the moment). https://luv-sense-digital.readthedocs.io

And the game assets with early stage codes can be found in this repo: https://e.coding.net/project-lsd/lsd/game.git
